global:
  resolve_timeout: 5m

route:
  receiver: default-devnull
  group_by: ["alertname", "service", "slo"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h
  routes:
    - matchers:
        - severity="critical"
      receiver: critical-notifications
      continue: true
    - matchers:
        - severity="warning"
      receiver: warning-notifications

inhibit_rules:
  - source_matchers:
      - alertname="RetailLivePricingTargetDown"
    target_matchers:
      - service="retail-live-pricing"
    equal: ["service"]

receivers:
  - name: default-devnull

  # Wire this to Slack webhook in real environments.
  - name: warning-notifications
    webhook_configs:
      - url: http://localhost:9999/alert-sink-warning
        send_resolved: true

  # Wire this to PagerDuty/Slack/email in real environments.
  - name: critical-notifications
    webhook_configs:
      - url: http://localhost:9999/alert-sink-critical
        send_resolved: true
